---
# tasks file for roles/testservers
- name: Add hosts file
  template: src=hosts.j2 dest=/etc/hosts mode=644 owner=root group=root

- name: Add SSHD config file
  template: src=sshd_config.j2 dest=/etc/ssh/sshd_config mode=644 owner=root group=root

- name: Add SSH banner
  template: src=ssh_banner.j2 dest=/etc/ssh/banner.txt mode=644 owner=root group=root

- name: Restart SSH Service
  service: name=sshd state=restarted
